---
collections:
- community.general
- community.postgresql
- community.mysql
- community.vmware  
# - redhat.satellite
- ansible.netcommon
- ansible.posix
- ansible.utils
- ansible.windows
- amazon.aws