---
- hosts: "{{ HOSTS | default('ec2-18-117-238-216.us-east-2.compute.amazonaws.com') }}"
  connection: local
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - name: Remove all hosts in inventory group "{{ node_group }}" from Satellite org "Default Organization"
    theforeman.foreman.host:
      name: "{{ item }}"
      state: absent
    with_items: "{{ groups[node_group] }}"
    register: remove_hosts_result
  - debug:
      var: remove_hosts_result
