---
- hosts: all
  gather_facts: no
  tasks:
  - name: Dynamically add ec2-18-117-238-216.us-east-2.compute.amazonaws.com to inventory
    add_host:
      name: ec2-18-117-238-216.us-east-2.compute.amazonaws.com

- hosts: ec2-18-117-238-216.us-east-2.compute.amazonaws.com
  connection: local
  gather_facts: no
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - set_fact:
      node_group: "env_{{ centos_lifecycle_environment }}"
  - name: Transfer hosts in Satellite LE "{{ centos_lifecycle_environment }}" to LE "{{ rhel_lifecycle_environment }}"
    theforeman.foreman.host:
      name: "{{ item }}"
      lifecycle_environment: "{{ rhel_lifecycle_environment }}"
      content_view: "{{ rhel_lifecycle_environment.split('_')[0] }}"
      organization: "{{ organization }}"
    with_items: "{{ groups[node_group] }}"
    register: transfer_hosts_result
  - debug:
      var: transfer_hosts_result
