---
- hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  vars:
    env: Dev
    activation_key: undef
    sat_url: ec2-18-117-238-216.us-east-2.compute.amazonaws.com
  roles:
    - rhsm_register
