---
- name: Take snapshot of instance
  hosts: ec2-52-91-213-25.compute-1.amazonaws.com
  # connection: local
  gather_facts: no
  vars:
    ec2_instance_action: "snapshot_create"
  roles:
    - ec2_node_tools

