---
- name: Take snapshot of instance
  hosts: ec2-54-86-58-244.compute-1.amazonaws.com
  # connection: local
  gather_facts: no
  tasks:
  - name: Take snapshot of instances in region "
    include_role:
      name: ec2_node_tools
    vars:
      ec2_instance_action: "snapshot_create"
